services:

  api:
    image: norttis/studiostudio-server:latest
    container_name: studiostudio_api
    env_file:
      - .env.docker
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
    depends_on:
      - postgres
      - redis
    volumes:
      - ./uploads:/app/wwwroot/uploads
    networks:
      - studiostudio_net

  postgres:
    image: postgres:17
    container_name: studiostudio_postgres
    env_file:
      - .env.docker
    restart: unless-stopped
    environment:
      POSTGRES_DB: study_studio
      POSTGRES_USER: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - studiostudio_net

  redis:
    image: redis:7
    container_name: studiostudio_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - studiostudio_net


# -----------------------------
# Monitoring stack
# -----------------------------

#   prometheus:
#     image: prom/prometheus
#     container_name: studiostudio_prometheus
#     ports:
#       - "9090:9090"
#     volumes:
#       - ./prometheus.yml:/etc/prometheus/prometheus.yml
#     networks:
#       - studiostudio_net

#   grafana:
#     image: grafana/grafana
#     container_name: studiostudio_grafana
#     ports:
#       - "3000:3000"
#     volumes:
#       - grafana_data:/var/lib/grafana
#     networks:
#       - studiostudio_net

#   node-exporter:
#     image: prom/node-exporter
#     container_name: studiostudio_node_exporter
#     ports:
#       - "9100:9100"
#     networks:
#       - studiostudio_net

#   cadvisor:
#     image: gcr.io/cadvisor/cadvisor
#     container_name: studiostudio_cadvisor
#     ports:
#       - "8081:8080"
#     volumes:
#       - /:/rootfs:ro
#       - /var/run:/var/run:ro
#       - /sys:/sys:ro
#       - /var/lib/docker/:/var/lib/docker:ro
#     networks:
#       - studiostudio_net


volumes:
  postgres_data:
  redis_data:
#   grafana_data:

networks:
  studiostudio_net:
    driver: bridge
